# This file was automatically generated by SDx
if { ![info exists _is_init_cmds] } {
  set vivado_error_file vivado_error.txt
  set vivado_warn_file vivado_warning.txt

  source ../../../.local/ocl_util.tcl
  namespace import ocl_util::*

  set _is_init_cmds true
}


# generate cookie file for messaging
write_cookie_file_impl ""

# utilization reports
report_utilization_impl false "conv2d_1 adapter" "routed"


# run timing analysis and frequency scaling
if { ![report_timing_and_scale_freq "" "true" "dr" "../../../output" "kernel_clock_freqs {clk_wiz_0_clk_out1 {is_user_set false clk_id 0 freq 74.992500} clk_wiz_0_clk_out2 {is_user_set false clk_id 1 freq 99.990000} clk_wiz_0_clk_out3 {is_user_set false clk_id 2 freq 149.985000} clk_wiz_0_clk_out4 {is_user_set false clk_id 3 freq 199.980000} clk_wiz_0_clk_out5 {is_user_set false clk_id 4 freq 299.970000} clk_wiz_0_clk_out6 {is_user_set false clk_id 5 freq 399.960000} clk_wiz_0_clk_out7 {is_user_set false clk_id 6 freq 599.940000}} system_clock_freqs {} worst_negative_slack 0 max_frequency 500 min_frequency 60 error_on_hold_violation true skip_timing_and_scaling false enable_auto_freq_scale false" ""] } {
  return false
}
