#include "hls_half.h"
#pragma SDS data mem_attribute(CON_IN2:PHYSICAL_CONTIGUOUS, KER2:PHYSICAL_CONTIGUOUS, CON_OUT2:PHYSICAL_CONTIGUOUS, BIA2:PHYSICAL_CONTIGUOUS)
#pragma SDS data data_mover(CON_IN2:AXIDMA_SIMPLE, KER2:AXIDMA_SIMPLE, CON_OUT2:AXIDMA_SIMPLE, BIA2:AXIDMA_SIMPLE)
#pragma SDS data access_pattern(CON_IN2:SEQUENTIAL, KER2:SEQUENTIAL, CON_OUT2:SEQUENTIAL, BIA2:SEQUENTIAL )

void conv2d_2(half CON_IN2[42240], half KER2[36864], half CON_OUT2[32768], half BIA2[64]);
